version: '3'
services:
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs:/var/log/nginx
            - ./..:/app
        ports:
            - 8080:80
    php:
        image: mp091689/php:latest
        restart: always
        volumes:
            - ./..:/app
            - ~/.gitconfig:/home/dev/.gitconfig:ro
            - ~/.ssh/id_rsa:/home/dev/.ssh/id_rsa:ro
            - ~/.ssh/id_rsa.pub:/home/dev/.ssh/id_rsa.pub:ro
