version: '3'
services:
    nginx:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./logs:/var/log/nginx
            - ./..:/app
        ports:
            - 8080:80
    php:
        image: testphp74:latest
        restart: always
        volumes:
            - ./..:/app
            - ~/.gitconfig:/home/dev/.gitconfig:ro
            - ~/.ssh/id_rsa:/home/dev/.ssh/id_rsa:ro
            - ~/.ssh/id_rsa.pub:/home/dev/.ssh/id_rsa.pub:ro
    mq:
        image: rabbitmq:3-management
        restart: always
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
            - 15672:15672
            - 5672:5672
        volumes:
            - ./mq/rabbitmq:/var/lib/rabbitmq